version: 0.2

phases:
  pre_build:
    commands:
      - cd ui
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo "REACT_APP_SERVICE_ID=\"$EMAILJS_SERVICE_ID\"" >> .env.production
      - echo "REACT_APP_TEMPLATE_ID=\"$EMAILJS_TEMPLATE_ID\"" >> .env.production
      - echo "REACT_APP_API_KEY=\"$EMAILJS_API_KEY\"" >> .env.production
      - npm run build:production

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  base-directory: ui/build