version: 0.2

phases:
  pre_build:
    commands:
      - sudo su
      - cd backend
      - cd ibe
  build:
    commands:
      - mvn clean install -Dspring-boot.run.arguments=--spring.datasource.url=jdbc:mysql://$DB_HOST:3306/ibe,--spring.datasource.username=$DB_USERNAME,--spring.datasource.password=$DB_PASSWORD,--cloud.aws.appsync.emailjs-user_id=$EMAILJS_API_KEY,--cloud.aws.appsync.emailjs-service_id=$EMAILJS_SERVICE_ID,--cloud.aws.appsync.emailjs-template_id=$EMAILJS_TEMPLATE_ID,--cloud.aws.appsync.emailjs-template_id_otp=$EMAILJS_TEMPLATE_ID_OTP,--cloud.aws.appsync.emailjs-accessToken=$EMAILJS_ACCESS_TOKEN,--cloud.aws.appsync.base-url=$APPSYNC_BASE_URL,--cloud.aws.appsync.api-key=$APPSYNC_API_KEY
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws --profile rohit_ghosh_mfa configure set aws_access_key_id "$ACCESS_KEY"
      - aws --profile rohit_ghosh_mfa configure set aws_secret_access_key "$SECRET_ACCESS_KEY"
      - aws --profile rohit_ghosh_mfa configure set aws_session_token "$SESSION_TOKEN"
      - aws ecr-public get-login-password --region us-east-1 --profile rohit_ghosh_mfa | docker login --username AWS --password-stdin public.ecr.aws/t5q7l3e2/ibe-t5-be-prod
      - REPOSITORY_URI=public.ecr.aws/t5q7l3e2/ibe-t5-be-prod
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=latest
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile.production --build-arg DB_HOST=$DB_HOST --build-arg DB_USERNAME=$DB_USERNAME --build-arg DB_PASSWORD=$DB_PASSWORD --build-arg APPSYNC_BASE_URL=$APPSYNC_BASE_URL --build-arg APPSYNC_API_KEY=$APPSYNC_API_KEY --build-arg EMAILJS_API_KEY=$EMAILJS_API_KEY --build-arg EMAILJS_SERVICE_ID=$EMAILJS_SERVICE_ID --build-arg EMAILJS_TEMPLATE_ID=$EMAILJS_TEMPLATE_ID --build-arg EMAILJS_TEMPLATE_ID_OTP=$EMAILJS_TEMPLATE_ID_OTP --build-arg EMAILJS_ACCESS_TOKEN=$EMAILJS_ACCESS_TOKEN -t ibe-t5-be-prod .
      - echo Tagging the docker image...
      - docker tag ibe-t5-be-prod:latest public.ecr.aws/t5q7l3e2/ibe-t5-be-prod:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/t5q7l3e2/ibe-t5-be-prod:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ibe-t5-be-production-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - target/ibe-0.0.1-SNAPSHOT.jar
  base-directory: backend/ibe