spring:
  application:
    name: prodApp
  datasource:
    initialization-mode: always
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
app:
  name: Welcome to prod

cloud:
  aws:
    appsync:
      base-url: base
      api-key: key
      emailjs-url: https://api.emailjs.com/api/v1.0/email/send
      emailjs-lib_version: 3.7.0
      emailjs-user_id: uid
      emailjs-service_id: sid
      emailjs-template_id: tid
      emailjs-accessToken: at
      emailjs-template_id_otp: tidotp

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE